name: build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Build application
        run: make

      - name: Test
        run: make test

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code
